using UnityEditor;

namespace JeffGrawAssets.FlexibleUI
{
public class ProceduralPropertiesEditor
{
    public readonly int AnimationStateIdx, AnimationStateSubIdx;
    public readonly ProceduralProperties ProceduralProperties;
    public readonly SerializedProperty BaseSerializedProperty;

    public SerializedProperty uvRectProperty;
    public SerializedProperty uvRectXProperty;
    public SerializedProperty uvRectYProperty;
    public SerializedProperty uvRectZProperty;
    public SerializedProperty uvRectWProperty;
    public SerializedProperty primaryColorFadeProperty;
    public SerializedProperty cornerChamferProperty;
    public SerializedProperty cornerXChamferProperty;
    public SerializedProperty cornerYChamferProperty;
    public SerializedProperty cornerZChamferProperty;
    public SerializedProperty cornerWChamferProperty;
    public SerializedProperty collapsedCornerChamferProperty;
    public SerializedProperty cornerConcavityProperty;
    public SerializedProperty cornerXConcavityProperty;
    public SerializedProperty cornerYConcavityProperty;
    public SerializedProperty cornerZConcavityProperty;
    public SerializedProperty cornerWConcavityProperty;
    public SerializedProperty collapsedCornerConcavityProperty;
    public SerializedProperty collapseEdgeAmountProperty;
    public SerializedProperty collapseEdgeAmountAbsoluteProperty;
    public SerializedProperty collapseEdgePositionProperty;
    public SerializedProperty strokeProperty;
    public SerializedProperty softnessProperty;
    public SerializedProperty sizeModifierProperty;
    public SerializedProperty sizeModifierXProperty;
    public SerializedProperty sizeModifierYProperty;
    public SerializedProperty offsetProperty;
    public SerializedProperty offsetXProperty;
    public SerializedProperty offsetYProperty;
    public SerializedProperty rotationProperty;
    public SerializedProperty cutoutXProperty;
    public SerializedProperty cutoutYProperty;
    public SerializedProperty cutoutZProperty;
    public SerializedProperty cutoutWProperty;
    public SerializedProperty outlineWidthProperty;
    public SerializedProperty proceduralGradientPositionProperty;
    public SerializedProperty radialGradientSizeProperty;
    public SerializedProperty radialGradientStrengthProperty;
    public SerializedProperty angleGradientStrengthProperty;
    public SerializedProperty proceduralGradientAngleProperty;
    public SerializedProperty sdfGradientInnerDistanceProperty;
    public SerializedProperty sdfGradientOuterDistanceProperty;
    public SerializedProperty sdfGradientInnerReachProperty;
    public SerializedProperty sdfGradientOuterReachProperty;
    public SerializedProperty conicalGradientCurvatureProperty;
    public SerializedProperty conicalGradientTailStrengthProperty;
    public SerializedProperty noiseScaleProperty;
    public SerializedProperty noiseSeedProperty;
    public SerializedProperty noiseEdgeProperty;
    public SerializedProperty noiseStrengthProperty;
    public SerializedProperty proceduralGradientPointerStrengthProperty;
    public SerializedProperty patternDensityProperty;
    public SerializedProperty patternSpeedProperty;
    public SerializedProperty patternCellParamProperty;
    public SerializedProperty patternLineThicknessProperty;
    public SerializedProperty patternSpriteRotationProperty;
    public SerializedProperty primaryColorsProperty;
    public SerializedProperty primaryColorOffsetProperty;
    public SerializedProperty primaryColorRotationProperty;
    public SerializedProperty primaryColorScaleProperty;
    public SerializedProperty outlineColorsProperty;
    public SerializedProperty outlineColorOffsetProperty;
    public SerializedProperty outlineColorRotationProperty;
    public SerializedProperty outlineColorScaleProperty;
    public SerializedProperty proceduralGradientColorsProperty;
    public SerializedProperty proceduralGradientColorOffsetProperty;
    public SerializedProperty proceduralGradientColorRotationProperty;
    public SerializedProperty proceduralGradientColorScaleProperty;
    public SerializedProperty patternColorsProperty;
    public SerializedProperty patternColorOffsetProperty;
    public SerializedProperty patternColorRotationProperty;
    public SerializedProperty patternColorScaleProperty;

    public ProceduralPropertiesEditor(ProceduralAnimationState[] animationStatesList, SerializedProperty parentProp, int animationStateIdx, int animationStateSubIdx)
    {
        (AnimationStateIdx, AnimationStateSubIdx) = (animationStateIdx, animationStateSubIdx);
        ProceduralProperties = animationStatesList[animationStateIdx].proceduralProperties[animationStateSubIdx];
        BaseSerializedProperty = parentProp.FindPropertyRelative(nameof(QuadData.proceduralAnimationStates)).GetArrayElementAtIndex(AnimationStateIdx).FindPropertyRelative(nameof(ProceduralAnimationState.proceduralProperties)).GetArrayElementAtIndex(AnimationStateSubIdx);
        uvRectProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.uvRect));
        uvRectXProperty = uvRectProperty.FindPropertyRelative("x");
        uvRectYProperty = uvRectProperty.FindPropertyRelative("y");
        uvRectZProperty = uvRectProperty.FindPropertyRelative("z");
        uvRectWProperty = uvRectProperty.FindPropertyRelative("w");
        primaryColorFadeProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.primaryColorFade));
        outlineWidthProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.outlineWidth));
        cornerChamferProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.cornerChamfer));
        cornerXChamferProperty = cornerChamferProperty.FindPropertyRelative("x");
        cornerYChamferProperty = cornerChamferProperty.FindPropertyRelative("y");
        cornerZChamferProperty = cornerChamferProperty.FindPropertyRelative("z");
        cornerWChamferProperty = cornerChamferProperty.FindPropertyRelative("w");
        collapsedCornerChamferProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.collapsedCornerChamfer));
        cornerConcavityProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.cornerConcavity));
        cornerXConcavityProperty = cornerConcavityProperty.FindPropertyRelative("x");
        cornerYConcavityProperty = cornerConcavityProperty.FindPropertyRelative("y");
        cornerZConcavityProperty = cornerConcavityProperty.FindPropertyRelative("z");
        cornerWConcavityProperty = cornerConcavityProperty.FindPropertyRelative("w");
        collapsedCornerConcavityProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.collapsedCornerConcavity));
        collapseEdgeAmountProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.collapseEdgeAmount));
        collapseEdgeAmountAbsoluteProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.collapseEdgeAmountAbsolute));
        collapseEdgePositionProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.collapseEdgePosition));
        strokeProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.stroke));
        softnessProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.softness));
        offsetProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.offset));
        offsetXProperty = offsetProperty.FindPropertyRelative("x");
        offsetYProperty = offsetProperty.FindPropertyRelative("y");
        sizeModifierProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.sizeModifier));
        sizeModifierXProperty = sizeModifierProperty.FindPropertyRelative("x");
        sizeModifierYProperty = sizeModifierProperty.FindPropertyRelative("y");
        rotationProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.rotation));
        cutoutXProperty = BaseSerializedProperty.FindPropertyRelative($"{nameof(ProceduralProperties.cutout)}.x");
        cutoutYProperty = BaseSerializedProperty.FindPropertyRelative($"{nameof(ProceduralProperties.cutout)}.y");
        cutoutZProperty = BaseSerializedProperty.FindPropertyRelative($"{nameof(ProceduralProperties.cutout)}.z");
        cutoutWProperty = BaseSerializedProperty.FindPropertyRelative($"{nameof(ProceduralProperties.cutout)}.w");
        proceduralGradientPositionProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.proceduralGradientPosition));
        radialGradientSizeProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.radialGradientSize));
        radialGradientStrengthProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.radialGradientStrength));
        angleGradientStrengthProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.angleGradientStrength));
        proceduralGradientAngleProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.proceduralGradientAngle));
        sdfGradientInnerDistanceProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.sdfGradientInnerDistance));
        sdfGradientOuterDistanceProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.sdfGradientOuterDistance));
        sdfGradientInnerReachProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.sdfGradientInnerReach));
        sdfGradientOuterReachProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.sdfGradientOuterReach));
        sdfGradientOuterReachProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.sdfGradientOuterReach));
        conicalGradientCurvatureProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.conicalGradientCurvature));
        conicalGradientTailStrengthProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.conicalGradientTailStrength));
        noiseScaleProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.noiseScale));
        noiseSeedProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.noiseSeed));
        noiseEdgeProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.noiseEdge));
        noiseStrengthProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.noiseStrength));
        proceduralGradientPointerStrengthProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.proceduralGradientPointerStrength));
        patternDensityProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.patternDensity));
        patternSpeedProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.patternSpeed));
        patternCellParamProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.patternCellParam));
        patternLineThicknessProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.patternLineThickness));
        patternSpriteRotationProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.patternSpriteRotation));
        primaryColorsProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.primaryColors));
        primaryColorOffsetProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.primaryColorOffset));
        primaryColorRotationProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.primaryColorRotation));
        primaryColorScaleProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.primaryColorScale));
        outlineColorsProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.outlineColors));
        outlineColorOffsetProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.outlineColorOffset));
        outlineColorRotationProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.outlineColorRotation));
        outlineColorScaleProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.outlineColorScale));
        proceduralGradientColorsProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.proceduralGradientColors));
        proceduralGradientColorOffsetProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.proceduralGradientColorOffset));
        proceduralGradientColorRotationProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.proceduralGradientColorRotation));
        proceduralGradientColorScaleProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.proceduralGradientColorScale));
        patternColorsProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.patternColors));
        patternColorOffsetProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.patternColorOffset));
        patternColorRotationProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.patternColorRotation));
        patternColorScaleProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.patternColorScale));
    }
}
}
